id = "apisartisan"
name = "ApisArtisan"
version = "0.0.1"
schema_version = 1
authors = ["TCeason <taichong357@gmail.com>"]
description = "A simple and pleasant dark theme for Zed"
repository = "https://github.com/TCeason/zed-theme"
